name: "Feature Branch"

on:
  push:
    branches-ignore:
      - main

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: feature-branch-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-tests:
    uses: ./.github/workflows/static-tests.trigger.yml
    secrets:
      GLOBAL_JFROG_ARTIFACTORY_TOKEN: ${{ secrets.GLOBAL_JFROG_ARTIFACTORY_TOKEN }}
    with:
      node_version: 14
  upload-images:
    uses: ./.github/workflows/upload-images.trigger.yml
    with: 
      env: dev
      node_version: 14
    secrets:
      GLOBAL_JFROG_ARTIFACTORY_TOKEN: ${{ secrets.GLOBAL_JFROG_ARTIFACTORY_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
