name: Upload images
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: environment to deploy
        default: prod
        options: 
        - stage
        - prod
        required: true

jobs:
  upload-images:
    uses: ./.github/workflows/upload-images.trigger.yml
    with: 
      env: ${{ github.event.inputs.env }}
      node_version: 14
    secrets:
      GLOBAL_JFROG_ARTIFACTORY_TOKEN: ${{ secrets.GLOBAL_JFROG_ARTIFACTORY_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  